# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/template/lab5.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(680, 480)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 661, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.xy_gview = L5GraphicsView(self.gridLayoutWidget)
        self.xy_gview.setObjectName("xy_gview")
        self.gridLayout_2.addWidget(self.xy_gview, 0, 0, 1, 1)
        self.xz_gview = L5GraphicsView(self.gridLayoutWidget)
        self.xz_gview.setObjectName("xz_gview")
        self.gridLayout_2.addWidget(self.xz_gview, 1, 0, 1, 1)
        self.yz_gview = L5GraphicsView(self.gridLayoutWidget)
        self.yz_gview.setObjectName("yz_gview")
        self.gridLayout_2.addWidget(self.yz_gview, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setEnabled(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.z_spin_ledit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.z_spin_ledit.setObjectName("z_spin_ledit")
        self.gridLayout_3.addWidget(self.z_spin_ledit, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 4, 4, 1, 1)
        self.x_spin_ledit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.x_spin_ledit.setObjectName("x_spin_ledit")
        self.gridLayout_3.addWidget(self.x_spin_ledit, 1, 1, 1, 1)
        self.z_move_ledit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.z_move_ledit.setObjectName("z_move_ledit")
        self.gridLayout_3.addWidget(self.z_move_ledit, 3, 4, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 0, 2, 6, 1)
        self.x_move_ledit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.x_move_ledit.setObjectName("x_move_ledit")
        self.gridLayout_3.addWidget(self.x_move_ledit, 1, 4, 1, 1)
        self.y_spin_ledit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.y_spin_ledit.setObjectName("y_spin_ledit")
        self.gridLayout_3.addWidget(self.y_spin_ledit, 2, 1, 1, 1)
        self.spin_pb = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.spin_pb.setObjectName("spin_pb")
        self.gridLayout_3.addWidget(self.spin_pb, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 3, 1, 1)
        self.y_move_ledit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.y_move_ledit.setObjectName("y_move_ledit")
        self.gridLayout_3.addWidget(self.y_move_ledit, 2, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 4, 1, 1)
        self.move_pb = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.move_pb.setObjectName("move_pb")
        self.gridLayout_3.addWidget(self.move_pb, 5, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "Z"))
        self.label_3.setText(_translate("Form", "X"))
        self.z_spin_ledit.setText(_translate("Form", "0"))
        self.x_spin_ledit.setText(_translate("Form", "0"))
        self.z_move_ledit.setText(_translate("Form", "0"))
        self.x_move_ledit.setText(_translate("Form", "0"))
        self.y_spin_ledit.setText(_translate("Form", "0"))
        self.spin_pb.setText(_translate("Form", "Повернуть"))
        self.label_6.setText(_translate("Form", "X"))
        self.y_move_ledit.setText(_translate("Form", "0"))
        self.label_2.setText(_translate("Form", "Перемещение"))
        self.move_pb.setText(_translate("Form", "Переместить"))
        self.label.setText(_translate("Form", "Вращение"))
        self.label_4.setText(_translate("Form", "Y"))
        self.label_8.setText(_translate("Form", "Z"))
        self.label_7.setText(_translate("Form", "Y"))

from l5graphicsview import L5GraphicsView
