# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/templates/lab2_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 647)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 621, 631))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = MyGraphicsView(self.gridLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.gridLayoutWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(9, 9, 601, 271))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.from_x_ledit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.from_x_ledit.setObjectName("from_x_ledit")
        self.gridLayout_2.addWidget(self.from_x_ledit, 1, 1, 1, 1)
        self.to_x_ledit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.to_x_ledit.setObjectName("to_x_ledit")
        self.gridLayout_2.addWidget(self.to_x_ledit, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.a_ledit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.a_ledit.setObjectName("a_ledit")
        self.gridLayout_2.addWidget(self.a_ledit, 0, 1, 1, 1)
        self.num_ledit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.num_ledit.setObjectName("num_ledit")
        self.gridLayout_2.addWidget(self.num_ledit, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.build_pb = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.build_pb.setObjectName("build_pb")
        self.horizontalLayout.addWidget(self.build_pb)
        self.gridLayout_2.addLayout(self.horizontalLayout, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 4, 0, 2, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(9, 9, 601, 271))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setEnabled(True)
        self.label_6.setMinimumSize(QtCore.QSize(0, 22))
        self.label_6.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_5.setEnabled(True)
        self.label_5.setMinimumSize(QtCore.QSize(0, 22))
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.move_x_ledit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.move_x_ledit.setObjectName("move_x_ledit")
        self.verticalLayout_3.addWidget(self.move_x_ledit)
        self.move_y_ledit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.move_y_ledit.setObjectName("move_y_ledit")
        self.verticalLayout_3.addWidget(self.move_y_ledit)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.move_pb = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.move_pb.setObjectName("move_pb")
        self.verticalLayout_3.addWidget(self.move_pb)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setMinimumSize(QtCore.QSize(0, 23))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_9.setMinimumSize(QtCore.QSize(0, 23))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_8.setMinimumSize(QtCore.QSize(0, 23))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_6.addItem(spacerItem7)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.rotate_x_ledit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.rotate_x_ledit.setObjectName("rotate_x_ledit")
        self.verticalLayout_7.addWidget(self.rotate_x_ledit)
        self.rotate_y_ledit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.rotate_y_ledit.setObjectName("rotate_y_ledit")
        self.verticalLayout_7.addWidget(self.rotate_y_ledit)
        self.rotate_angle_ledit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.rotate_angle_ledit.setObjectName("rotate_angle_ledit")
        self.verticalLayout_7.addWidget(self.rotate_angle_ledit)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem8)
        self.rotate_pb = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.rotate_pb.setObjectName("rotate_pb")
        self.verticalLayout_7.addWidget(self.rotate_pb)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.from_x_ledit.setText(_translate("Form", "-200"))
        self.to_x_ledit.setText(_translate("Form", "200"))
        self.label_2.setText(_translate("Form", "от Х"))
        self.a_ledit.setText(_translate("Form", "30"))
        self.num_ledit.setText(_translate("Form", "100"))
        self.label_3.setText(_translate("Form", "до Х"))
        self.build_pb.setText(_translate("Form", "Построить"))
        self.label_4.setText(_translate("Form", "количество точек"))
        self.label.setText(_translate("Form", "а"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Построение"))
        self.label_6.setText(_translate("Form", "X"))
        self.label_5.setText(_translate("Form", "Y"))
        self.move_x_ledit.setText(_translate("Form", "0"))
        self.move_y_ledit.setText(_translate("Form", "0"))
        self.move_pb.setText(_translate("Form", "Переместить"))
        self.label_7.setText(_translate("Form", "X"))
        self.label_9.setText(_translate("Form", "Y"))
        self.label_8.setText(_translate("Form", "угол поворота"))
        self.rotate_x_ledit.setText(_translate("Form", "0"))
        self.rotate_y_ledit.setText(_translate("Form", "0"))
        self.rotate_angle_ledit.setText(_translate("Form", "0"))
        self.rotate_pb.setText(_translate("Form", "Вращать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Преобразование"))

from mygraphicsview import MyGraphicsView
