# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/templates/lab6_form.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 621, 461))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graphicsView = MyGraphicsView(self.horizontalLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.x_angle_ledit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.x_angle_ledit.setObjectName("x_angle_ledit")
        self.gridLayout.addWidget(self.x_angle_ledit, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.z_angle_ledit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.z_angle_ledit.setObjectName("z_angle_ledit")
        self.gridLayout.addWidget(self.z_angle_ledit, 2, 1, 1, 1)
        self.y_angle_ledit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.y_angle_ledit.setObjectName("y_angle_ledit")
        self.gridLayout.addWidget(self.y_angle_ledit, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.rotate_pb = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.rotate_pb.setObjectName("rotate_pb")
        self.gridLayout.addWidget(self.rotate_pb, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.move_right_pb = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.move_right_pb.setObjectName("move_right_pb")
        self.gridLayout_2.addWidget(self.move_right_pb, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 1)
        self.move_left_pb = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.move_left_pb.setObjectName("move_left_pb")
        self.gridLayout_2.addWidget(self.move_left_pb, 1, 0, 1, 1)
        self.move_up_pb = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.move_up_pb.setObjectName("move_up_pb")
        self.gridLayout_2.addWidget(self.move_up_pb, 0, 1, 1, 1)
        self.move_down_pb = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.move_down_pb.setObjectName("move_down_pb")
        self.gridLayout_2.addWidget(self.move_down_pb, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Y"))
        self.x_angle_ledit.setText(_translate("Form", "0"))
        self.label_3.setText(_translate("Form", "Z"))
        self.z_angle_ledit.setText(_translate("Form", "0"))
        self.y_angle_ledit.setText(_translate("Form", "0"))
        self.label.setText(_translate("Form", "X"))
        self.rotate_pb.setText(_translate("Form", "Rotate"))
        self.move_right_pb.setText(_translate("Form", "RIGHT"))
        self.move_left_pb.setText(_translate("Form", "LEFT"))
        self.move_up_pb.setText(_translate("Form", "UP"))
        self.move_down_pb.setText(_translate("Form", "DOWN"))

from mygraphicsview import MyGraphicsView
