# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/templates/form_v2.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 1000)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = MyGraphicsView(Form)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 10, 2, 1, 1)
        self.draw_lab0_btn = QtWidgets.QPushButton(self.tab)
        self.draw_lab0_btn.setObjectName("draw_lab0_btn")
        self.gridLayout_2.addWidget(self.draw_lab0_btn, 11, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 11, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../test.jpg"))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 12, 1)
        self.diag_size_lbl = QtWidgets.QLabel(self.tab)
        self.diag_size_lbl.setObjectName("diag_size_lbl")
        self.gridLayout_2.addWidget(self.diag_size_lbl, 0, 1, 1, 2)
        self.diag_size_ledit = QtWidgets.QLineEdit(self.tab)
        self.diag_size_ledit.setObjectName("diag_size_ledit")
        self.gridLayout_2.addWidget(self.diag_size_ledit, 1, 1, 1, 2)
        self.big_rad_lbl = QtWidgets.QLabel(self.tab)
        self.big_rad_lbl.setObjectName("big_rad_lbl")
        self.gridLayout_2.addWidget(self.big_rad_lbl, 2, 1, 1, 2)
        self.big_rad_ledit = QtWidgets.QLineEdit(self.tab)
        self.big_rad_ledit.setObjectName("big_rad_ledit")
        self.gridLayout_2.addWidget(self.big_rad_ledit, 3, 1, 1, 2)
        self.lit_rad_lbl = QtWidgets.QLabel(self.tab)
        self.lit_rad_lbl.setObjectName("lit_rad_lbl")
        self.gridLayout_2.addWidget(self.lit_rad_lbl, 4, 1, 1, 2)
        self.lit_rad_ledit = QtWidgets.QLineEdit(self.tab)
        self.lit_rad_ledit.setObjectName("lit_rad_ledit")
        self.gridLayout_2.addWidget(self.lit_rad_ledit, 5, 1, 1, 2)
        self.hor_rad_lbl = QtWidgets.QLabel(self.tab)
        self.hor_rad_lbl.setObjectName("hor_rad_lbl")
        self.gridLayout_2.addWidget(self.hor_rad_lbl, 6, 1, 1, 2)
        self.hor_rad_ledit = QtWidgets.QLineEdit(self.tab)
        self.hor_rad_ledit.setObjectName("hor_rad_ledit")
        self.gridLayout_2.addWidget(self.hor_rad_ledit, 7, 1, 1, 2)
        self.ver_rad_lbl = QtWidgets.QLabel(self.tab)
        self.ver_rad_lbl.setObjectName("ver_rad_lbl")
        self.gridLayout_2.addWidget(self.ver_rad_lbl, 8, 1, 1, 2)
        self.ver_rad_ledit = QtWidgets.QLineEdit(self.tab)
        self.ver_rad_ledit.setObjectName("ver_rad_ledit")
        self.gridLayout_2.addWidget(self.ver_rad_ledit, 9, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 10, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.mv_axis_y_evk_ledit = QtWidgets.QLineEdit(self.tab_8)
        self.mv_axis_y_evk_ledit.setObjectName("mv_axis_y_evk_ledit")
        self.gridLayout_6.addWidget(self.mv_axis_y_evk_ledit, 1, 1, 1, 1)
        self.mv_axis_x_evk_ledit = QtWidgets.QLineEdit(self.tab_8)
        self.mv_axis_x_evk_ledit.setObjectName("mv_axis_x_evk_ledit")
        self.gridLayout_6.addWidget(self.mv_axis_x_evk_ledit, 1, 0, 1, 1)
        self.move_evk_btn = QtWidgets.QPushButton(self.tab_8)
        self.move_evk_btn.setObjectName("move_evk_btn")
        self.gridLayout_6.addWidget(self.move_evk_btn, 1, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.tab_8)
        self.label_16.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_8)
        self.label_14.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 1, 2, 1, 2)
        self.rotate_evk_btn = QtWidgets.QPushButton(self.tab_8)
        self.rotate_evk_btn.setObjectName("rotate_evk_btn")
        self.gridLayout_6.addWidget(self.rotate_evk_btn, 3, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_8)
        self.label_15.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 2, 1, 1, 1)
        self.rt_angle_evk_ledit = QtWidgets.QLineEdit(self.tab_8)
        self.rt_angle_evk_ledit.setObjectName("rt_angle_evk_ledit")
        self.gridLayout_6.addWidget(self.rt_angle_evk_ledit, 3, 2, 1, 1)
        self.rt_x_center_evk_ledit = QtWidgets.QLineEdit(self.tab_8)
        self.rt_x_center_evk_ledit.setObjectName("rt_x_center_evk_ledit")
        self.gridLayout_6.addWidget(self.rt_x_center_evk_ledit, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 3, 3, 1, 1)
        self.rt_y_center_evk_ledit = QtWidgets.QLineEdit(self.tab_8)
        self.rt_y_center_evk_ledit.setObjectName("rt_y_center_evk_ledit")
        self.gridLayout_6.addWidget(self.rt_y_center_evk_ledit, 3, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_8)
        self.label_17.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_8)
        self.label_18.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 0, 1, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_6)
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_9)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.vec_y_1_ledit = QtWidgets.QLineEdit(self.tab_9)
        self.vec_y_1_ledit.setObjectName("vec_y_1_ledit")
        self.gridLayout_4.addWidget(self.vec_y_1_ledit, 1, 3, 1, 1)
        self.vec_r0_2_ledit = QtWidgets.QLineEdit(self.tab_9)
        self.vec_r0_2_ledit.setObjectName("vec_r0_2_ledit")
        self.gridLayout_4.addWidget(self.vec_r0_2_ledit, 2, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_9)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 1, 1, 1)
        self.vec_r0_0_ledit = QtWidgets.QLineEdit(self.tab_9)
        self.vec_r0_0_ledit.setObjectName("vec_r0_0_ledit")
        self.gridLayout_4.addWidget(self.vec_r0_0_ledit, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_9)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 1, 1, 1)
        self.vec_y_0_ledit = QtWidgets.QLineEdit(self.tab_9)
        self.vec_y_0_ledit.setObjectName("vec_y_0_ledit")
        self.gridLayout_4.addWidget(self.vec_y_0_ledit, 1, 2, 1, 1)
        self.vec_x_0_ledit = QtWidgets.QLineEdit(self.tab_9)
        self.vec_x_0_ledit.setObjectName("vec_x_0_ledit")
        self.gridLayout_4.addWidget(self.vec_x_0_ledit, 0, 2, 1, 1)
        self.vec_x_2_ledit = QtWidgets.QLineEdit(self.tab_9)
        self.vec_x_2_ledit.setObjectName("vec_x_2_ledit")
        self.gridLayout_4.addWidget(self.vec_x_2_ledit, 0, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_9)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 2, 1, 1, 1)
        self.vec_r0_1_ledit = QtWidgets.QLineEdit(self.tab_9)
        self.vec_r0_1_ledit.setObjectName("vec_r0_1_ledit")
        self.gridLayout_4.addWidget(self.vec_r0_1_ledit, 2, 3, 1, 1)
        self.vec_x_1_ledit = QtWidgets.QLineEdit(self.tab_9)
        self.vec_x_1_ledit.setObjectName("vec_x_1_ledit")
        self.gridLayout_4.addWidget(self.vec_x_1_ledit, 0, 3, 1, 1)
        self.vec_y_2_ledit = QtWidgets.QLineEdit(self.tab_9)
        self.vec_y_2_ledit.setObjectName("vec_y_2_ledit")
        self.gridLayout_4.addWidget(self.vec_y_2_ledit, 1, 4, 1, 1)
        self.draw_lab1_transform_btn = QtWidgets.QPushButton(self.tab_9)
        self.draw_lab1_transform_btn.setObjectName("draw_lab1_transform_btn")
        self.gridLayout_4.addWidget(self.draw_lab1_transform_btn, 1, 0, 1, 1)
        self.transform_lab1_transform_btn = QtWidgets.QPushButton(self.tab_9)
        self.transform_lab1_transform_btn.setObjectName("transform_lab1_transform_btn")
        self.gridLayout_4.addWidget(self.transform_lab1_transform_btn, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_4)
        self.tabWidget_2.addTab(self.tab_9, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ry_1_afin_ledit = QtWidgets.QLineEdit(self.tab_10)
        self.ry_1_afin_ledit.setObjectName("ry_1_afin_ledit")
        self.gridLayout_5.addWidget(self.ry_1_afin_ledit, 1, 3, 1, 1)
        self.rx_0_afin_ledit = QtWidgets.QLineEdit(self.tab_10)
        self.rx_0_afin_ledit.setObjectName("rx_0_afin_ledit")
        self.gridLayout_5.addWidget(self.rx_0_afin_ledit, 0, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_10)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 1, 1, 1)
        self.r0_1_afin_ledit = QtWidgets.QLineEdit(self.tab_10)
        self.r0_1_afin_ledit.setObjectName("r0_1_afin_ledit")
        self.gridLayout_5.addWidget(self.r0_1_afin_ledit, 2, 3, 1, 1)
        self.rx_1_afin_ledit = QtWidgets.QLineEdit(self.tab_10)
        self.rx_1_afin_ledit.setObjectName("rx_1_afin_ledit")
        self.gridLayout_5.addWidget(self.rx_1_afin_ledit, 0, 3, 1, 1)
        self.r0_0_afin_ledit = QtWidgets.QLineEdit(self.tab_10)
        self.r0_0_afin_ledit.setObjectName("r0_0_afin_ledit")
        self.gridLayout_5.addWidget(self.r0_0_afin_ledit, 2, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_10)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 1, 1, 1, 1)
        self.ry_0_afin_ledit = QtWidgets.QLineEdit(self.tab_10)
        self.ry_0_afin_ledit.setObjectName("ry_0_afin_ledit")
        self.gridLayout_5.addWidget(self.ry_0_afin_ledit, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_10)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 2, 1, 1, 1)
        self.draw_lab1_afin_btn = QtWidgets.QPushButton(self.tab_10)
        self.draw_lab1_afin_btn.setObjectName("draw_lab1_afin_btn")
        self.gridLayout_5.addWidget(self.draw_lab1_afin_btn, 1, 0, 1, 1)
        self.transform_lab1_afin_btn = QtWidgets.QPushButton(self.tab_10)
        self.transform_lab1_afin_btn.setObjectName("transform_lab1_afin_btn")
        self.gridLayout_5.addWidget(self.transform_lab1_afin_btn, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 0, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_5)
        self.tabWidget_2.addTab(self.tab_10, "")
        self.gridLayout_3.addWidget(self.tabWidget_2, 0, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget.addTab(self.tab_7, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.draw_lab0_btn.setText(_translate("Form", "Draw"))
        self.diag_size_lbl.setText(_translate("Form", "Введите размер диагонали D"))
        self.big_rad_lbl.setText(_translate("Form", "Введите радиус R"))
        self.lit_rad_lbl.setText(_translate("Form", "Введите радиус r"))
        self.hor_rad_lbl.setText(_translate("Form", "Введите радиус r1"))
        self.ver_rad_lbl.setText(_translate("Form", "Введите радиус r2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Lab 0"))
        self.move_evk_btn.setText(_translate("Form", "Перемещение"))
        self.label_16.setText(_translate("Form", "угол поворота"))
        self.label_14.setText(_translate("Form", "X"))
        self.rotate_evk_btn.setText(_translate("Form", "Поворот"))
        self.label_15.setText(_translate("Form", "Y"))
        self.label_17.setText(_translate("Form", "Ось Х"))
        self.label_18.setText(_translate("Form", "Ось Y"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("Form", "Евклидовы"))
        self.label_8.setText(_translate("Form", "X"))
        self.label_9.setText(_translate("Form", "Y"))
        self.label_10.setText(_translate("Form", "R0"))
        self.draw_lab1_transform_btn.setText(_translate("Form", "Draw"))
        self.transform_lab1_transform_btn.setText(_translate("Form", "Transform"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("Form", "Проективные"))
        self.label_11.setText(_translate("Form", "Rx"))
        self.label_12.setText(_translate("Form", "Ry"))
        self.label_13.setText(_translate("Form", "R0"))
        self.draw_lab1_afin_btn.setText(_translate("Form", "Draw"))
        self.transform_lab1_afin_btn.setText(_translate("Form", "Transform"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_10), _translate("Form", "Афинные"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Lab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Lab 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Lab 3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "Lab 4"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Form", "Lab 5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Form", "Lab 6"))

from mygraphicsview import MyGraphicsView
